name: Content Part Deploy

on:
  push:
    branches: [ dev, staging, prod, 'major:*', 'minor:*', 'patch:*' ]

  workflow_dispatch:
    inputs:
      version_type:
        description: "Choose version bump type: patch, minor, or major"
        required: false
        default: "patch"

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: NPM Install
      run: npm install

    - name: Set Git User
      run: |
        git config --global user.email "deepak.kushwaha@codinova.com"
        git config --global user.name "deepakcodinova"

    - name: Set Version Type
      run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ "$BRANCH_NAME" == major:* ]]; then
            echo "VERSION_TYPE=major" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == minor:* ]]; then
            echo "VERSION_TYPE=minor" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == patch:* ]]; then
            echo "VERSION_TYPE=patch" >> $GITHUB_ENV
          else
            echo "VERSION_TYPE=patch" >> $GITHUB_ENV
          fi

    - name: Run Version Update
      run: |
        if [[ "$VERSION_TYPE" == "major" ]]; then
          npm run generate:major
        elif [[ "$VERSION_TYPE" == "minor" ]]; then
          npm run generate:minor       
        else
          npm run generate:patch
        fi

    - name: Push changes
      run: |
        git push origin HEAD:${{ github.ref }}

    # Add your deployment steps here
    # For example:
    # - name: Deploy to Dev
    #   if: github.ref == 'refs/heads/dev'
    #   run: npm run deploy:dev
    
    # - name: Deploy to Staging
    #   if: github.ref == 'refs/heads/staging'
    #   run: npm run deploy:staging
    
    # - name: Deploy to Production
    #   if: github.ref == 'refs/heads/prod'
    #   run: npm run deploy:prod